# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from ..util import deserialize_model


class QueryStatus(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        QueryStatus - a model defined in Swagger

        """
        self.swagger_types = {
            
        }

        self.attribute_map = {
            
        }


    @classmethod
    def from_dict(cls, dikt) -> 'QueryStatus':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryStatus of this QueryStatus.
        :rtype: QueryStatus
        """
        return deserialize_model(dikt, cls)
