# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class QueryNextResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, result_set: str=None, next_token: str=None):
        """
        QueryNextResponse - a model defined in Swagger

        :param result_set: The result_set of this QueryNextResponse.
        :type result_set: str
        :param next_token: The next_token of this QueryNextResponse.
        :type next_token: str
        """
        self.swagger_types = {
            'result_set': str,
            'next_token': str
        }

        self.attribute_map = {
            'result_set': 'result_set',
            'next_token': 'next_token'
        }

        self._result_set = result_set
        self._next_token = next_token

    @classmethod
    def from_dict(cls, dikt) -> 'QueryNextResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryNextResponse of this QueryNextResponse.
        :rtype: QueryNextResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def result_set(self) -> str:
        """
        Gets the result_set of this QueryNextResponse.
        JSON query results (probably 1/N chunks)

        :return: The result_set of this QueryNextResponse.
        :rtype: str
        """
        return self._result_set

    @result_set.setter
    def result_set(self, result_set: str):
        """
        Sets the result_set of this QueryNextResponse.
        JSON query results (probably 1/N chunks)

        :param result_set: The result_set of this QueryNextResponse.
        :type result_set: str
        """

        self._result_set = result_set

    @property
    def next_token(self) -> str:
        """
        Gets the next_token of this QueryNextResponse.
        Token that demarcates the new row based on this result set chunk

        :return: The next_token of this QueryNextResponse.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token: str):
        """
        Sets the next_token of this QueryNextResponse.
        Token that demarcates the new row based on this result set chunk

        :param next_token: The next_token of this QueryNextResponse.
        :type next_token: str
        """

        self._next_token = next_token

