#standardSQL

# Second version of Account History Features, V2: aggregate together the feature results we have so far into 
#  a single wide table.

# only include tickets from Damien's original pull & join with all other result tables 

SELECT
  mct.tckt_ticketID,
  mct.created,
  mct.Account_Name,
  
  afq.final_q_tix_1,
  afq.final_q_tix_2,
  afq.final_q_tix_3,
  afq.final_q_tix_4,
  afq.final_q_tix_5,
  awd.wrk_dfy_max_1,
  awd.wrk_dfy_max_2,
  awd.wrk_dfy_max_3,
  awd.wrk_dfy_max_4,
  awd.wrk_dfy_max_5,
  awd.wrk_dfy_avg_1,
  awd.wrk_dfy_avg_2,
  awd.wrk_dfy_avg_3,
  awd.wrk_dfy_avg_4,
  awd.wrk_dfy_avg_5,
  atc.tix_cnt_1w,
  atc.tix_cnt_4w,
  atc.tix_cnt_16w,
  atc.tix_cnt_30w,
  
  awt5c.work_type_cnt_1_1,
  awt5c.work_type_cnt_1_2,
  awt5c.work_type_cnt_1_3,
  awt5c.work_type_cnt_1_4,
  awt5c.work_type_cnt_1_5,
  awt5c.work_type_cnt_wt_1_1,
  awt5c.work_type_cnt_wt_1_2,
  awt5c.work_type_cnt_wt_1_3,
  awt5c.work_type_cnt_wt_1_4,
  awt5c.work_type_cnt_wt_1_5,
  awt5c.work_type_cnt_2_1,
  awt5c.work_type_cnt_2_2,
  awt5c.work_type_cnt_2_3,
  awt5c.work_type_cnt_2_4,
  awt5c.work_type_cnt_2_5,
  awt5c.work_type_cnt_wt_2_1,
  awt5c.work_type_cnt_wt_2_2,
  awt5c.work_type_cnt_wt_2_3,
  awt5c.work_type_cnt_wt_2_4,
  awt5c.work_type_cnt_wt_2_5,
  awt5c.work_type_cnt_3_1,
  awt5c.work_type_cnt_3_2,
  awt5c.work_type_cnt_3_3,
  awt5c.work_type_cnt_3_4,
  awt5c.work_type_cnt_3_5,
  awt5c.work_type_cnt_wt_3_1,
  awt5c.work_type_cnt_wt_3_2,
  awt5c.work_type_cnt_wt_3_3,
  awt5c.work_type_cnt_wt_3_4,
  awt5c.work_type_cnt_wt_3_5,
  awt5c.work_type_cnt_4_1,
  awt5c.work_type_cnt_4_2,
  awt5c.work_type_cnt_4_3,
  awt5c.work_type_cnt_4_4,
  awt5c.work_type_cnt_4_5,
  awt5c.work_type_cnt_wt_4_1,
  awt5c.work_type_cnt_wt_4_2,
  awt5c.work_type_cnt_wt_4_3,
  awt5c.work_type_cnt_wt_4_4,
  awt5c.work_type_cnt_wt_4_5,
  awt5c.work_type_cnt_5_1,
  awt5c.work_type_cnt_5_2,
  awt5c.work_type_cnt_5_3,
  awt5c.work_type_cnt_5_4,
  awt5c.work_type_cnt_5_5,
  awt5c.work_type_cnt_wt_5_1,
  awt5c.work_type_cnt_wt_5_2,
  awt5c.work_type_cnt_wt_5_3,
  awt5c.work_type_cnt_wt_5_4,
  awt5c.work_type_cnt_wt_5_5,
  
  awt5dv.work_type_df_avg_1_1,
  awt5dv.work_type_df_avg_1_2,
  awt5dv.work_type_df_avg_1_3,
  awt5dv.work_type_df_avg_1_4,
  awt5dv.work_type_df_avg_1_5,
  awt5dv.work_type_df_avg_wt_1_1,
  awt5dv.work_type_df_avg_wt_1_2,
  awt5dv.work_type_df_avg_wt_1_3,
  awt5dv.work_type_df_avg_wt_1_4,
  awt5dv.work_type_df_avg_wt_1_5,
  awt5dv.work_type_df_avg_2_1,
  awt5dv.work_type_df_avg_2_2,
  awt5dv.work_type_df_avg_2_3,
  awt5dv.work_type_df_avg_2_4,
  awt5dv.work_type_df_avg_2_5,
  awt5dv.work_type_df_avg_wt_2_1,
  awt5dv.work_type_df_avg_wt_2_2,
  awt5dv.work_type_df_avg_wt_2_3,
  awt5dv.work_type_df_avg_wt_2_4,
  awt5dv.work_type_df_avg_wt_2_5,
  awt5dv.work_type_df_avg_3_1,
  awt5dv.work_type_df_avg_3_2,
  awt5dv.work_type_df_avg_3_3,
  awt5dv.work_type_df_avg_3_4,
  awt5dv.work_type_df_avg_3_5,
  awt5dv.work_type_df_avg_wt_3_1,
  awt5dv.work_type_df_avg_wt_3_2,
  awt5dv.work_type_df_avg_wt_3_3,
  awt5dv.work_type_df_avg_wt_3_4,
  awt5dv.work_type_df_avg_wt_3_5,
  awt5dv.work_type_df_avg_4_1,
  awt5dv.work_type_df_avg_4_2,
  awt5dv.work_type_df_avg_4_3,
  awt5dv.work_type_df_avg_4_4,
  awt5dv.work_type_df_avg_4_5,
  awt5dv.work_type_df_avg_wt_4_1,
  awt5dv.work_type_df_avg_wt_4_2,
  awt5dv.work_type_df_avg_wt_4_3,
  awt5dv.work_type_df_avg_wt_4_4,
  awt5dv.work_type_df_avg_wt_4_5,
  awt5dv.work_type_df_avg_5_1,
  awt5dv.work_type_df_avg_5_2,
  awt5dv.work_type_df_avg_5_3,
  awt5dv.work_type_df_avg_5_4,
  awt5dv.work_type_df_avg_5_5,
  awt5dv.work_type_df_avg_wt_5_1,
  awt5dv.work_type_df_avg_wt_5_2,
  awt5dv.work_type_df_avg_wt_5_3,
  awt5dv.work_type_df_avg_wt_5_4,
  awt5dv.work_type_df_avg_wt_5_5,
  
  awt5dm.work_type_df_max_1_1,
  awt5dm.work_type_df_max_1_2,
  awt5dm.work_type_df_max_1_3,
  awt5dm.work_type_df_max_1_4,
  awt5dm.work_type_df_max_1_5,
  awt5dm.work_type_df_max_wt_1_1,
  awt5dm.work_type_df_max_wt_1_2,
  awt5dm.work_type_df_max_wt_1_3,
  awt5dm.work_type_df_max_wt_1_4,
  awt5dm.work_type_df_max_wt_1_5,
  awt5dm.work_type_df_max_2_1,
  awt5dm.work_type_df_max_2_2,
  awt5dm.work_type_df_max_2_3,
  awt5dm.work_type_df_max_2_4,
  awt5dm.work_type_df_max_2_5,
  awt5dm.work_type_df_max_wt_2_1,
  awt5dm.work_type_df_max_wt_2_2,
  awt5dm.work_type_df_max_wt_2_3,
  awt5dm.work_type_df_max_wt_2_4,
  awt5dm.work_type_df_max_wt_2_5,
  awt5dm.work_type_df_max_3_1,
  awt5dm.work_type_df_max_3_2,
  awt5dm.work_type_df_max_3_3,
  awt5dm.work_type_df_max_3_4,
  awt5dm.work_type_df_max_3_5,
  awt5dm.work_type_df_max_wt_3_1,
  awt5dm.work_type_df_max_wt_3_2,
  awt5dm.work_type_df_max_wt_3_3,
  awt5dm.work_type_df_max_wt_3_4,
  awt5dm.work_type_df_max_wt_3_5,
  awt5dm.work_type_df_max_4_1,
  awt5dm.work_type_df_max_4_2,
  awt5dm.work_type_df_max_4_3,
  awt5dm.work_type_df_max_4_4,
  awt5dm.work_type_df_max_4_5,
  awt5dm.work_type_df_max_wt_4_1,
  awt5dm.work_type_df_max_wt_4_2,
  awt5dm.work_type_df_max_wt_4_3,
  awt5dm.work_type_df_max_wt_4_4,
  awt5dm.work_type_df_max_wt_4_5,
  awt5dm.work_type_df_max_5_1,
  awt5dm.work_type_df_max_5_2,
  awt5dm.work_type_df_max_5_3,
  awt5dm.work_type_df_max_5_4,
  awt5dm.work_type_df_max_5_5,
  awt5dm.work_type_df_max_wt_5_1,
  awt5dm.work_type_df_max_wt_5_2,
  awt5dm.work_type_df_max_wt_5_3,
  awt5dm.work_type_df_max_wt_5_4,
  awt5dm.work_type_df_max_wt_5_5,
  
  awt5du.work_type_dur_1_1,
  awt5du.work_type_dur_1_2,
  awt5du.work_type_dur_1_3,
  awt5du.work_type_dur_1_4,
  awt5du.work_type_dur_1_5,
  awt5du.work_type_dur_wt_1_1,
  awt5du.work_type_dur_wt_1_2,
  awt5du.work_type_dur_wt_1_3,
  awt5du.work_type_dur_wt_1_4,
  awt5du.work_type_dur_wt_1_5,
  awt5du.work_type_dur_2_1,
  awt5du.work_type_dur_2_2,
  awt5du.work_type_dur_2_3,
  awt5du.work_type_dur_2_4,
  awt5du.work_type_dur_2_5,
  awt5du.work_type_dur_wt_2_1,
  awt5du.work_type_dur_wt_2_2,
  awt5du.work_type_dur_wt_2_3,
  awt5du.work_type_dur_wt_2_4,
  awt5du.work_type_dur_wt_2_5,
  awt5du.work_type_dur_3_1,
  awt5du.work_type_dur_3_2,
  awt5du.work_type_dur_3_3,
  awt5du.work_type_dur_3_4,
  awt5du.work_type_dur_3_5,
  awt5du.work_type_dur_wt_3_1,
  awt5du.work_type_dur_wt_3_2,
  awt5du.work_type_dur_wt_3_3,
  awt5du.work_type_dur_wt_3_4,
  awt5du.work_type_dur_wt_3_5,
  awt5du.work_type_dur_4_1,
  awt5du.work_type_dur_4_2,
  awt5du.work_type_dur_4_3,
  awt5du.work_type_dur_4_4,
  awt5du.work_type_dur_4_5,
  awt5du.work_type_dur_wt_4_1,
  awt5du.work_type_dur_wt_4_2,
  awt5du.work_type_dur_wt_4_3,
  awt5du.work_type_dur_wt_4_4,
  awt5du.work_type_dur_wt_4_5,
  awt5du.work_type_dur_5_1,
  awt5du.work_type_dur_5_2,
  awt5du.work_type_dur_5_3,
  awt5du.work_type_dur_5_4,
  awt5du.work_type_dur_5_5,
  awt5du.work_type_dur_wt_5_1,
  awt5du.work_type_dur_wt_5_2,
  awt5du.work_type_dur_wt_5_3,
  awt5du.work_type_dur_wt_5_4,
  awt5du.work_type_dur_wt_5_5,
  
  awtpcn.wrk_typ_cnt_1w_1,
  awtpcn.wrk_typ_cnt_1w_2,
  awtpcn.wrk_typ_cnt_1w_3,
  awtpcn.wrk_typ_cnt_1w_4,
  awtpcn.wrk_typ_cnt_1w_5,
  awtpcn.wrk_typ_cnt_1w_wt_1,
  awtpcn.wrk_typ_cnt_1w_wt_2,
  awtpcn.wrk_typ_cnt_1w_wt_3,
  awtpcn.wrk_typ_cnt_1w_wt_4,
  awtpcn.wrk_typ_cnt_1w_wt_5,
  awtpcn.wrk_typ_cnt_4w_1,
  awtpcn.wrk_typ_cnt_4w_2,
  awtpcn.wrk_typ_cnt_4w_3,
  awtpcn.wrk_typ_cnt_4w_4,
  awtpcn.wrk_typ_cnt_4w_5,
  awtpcn.wrk_typ_cnt_4w_wt_1,
  awtpcn.wrk_typ_cnt_4w_wt_2,
  awtpcn.wrk_typ_cnt_4w_wt_3,
  awtpcn.wrk_typ_cnt_4w_wt_4,
  awtpcn.wrk_typ_cnt_4w_wt_5,
  awtpcn.wrk_typ_cnt_16w_1,
  awtpcn.wrk_typ_cnt_16w_2,
  awtpcn.wrk_typ_cnt_16w_3,
  awtpcn.wrk_typ_cnt_16w_4,
  awtpcn.wrk_typ_cnt_16w_5,
  awtpcn.wrk_typ_cnt_16w_wt_1,
  awtpcn.wrk_typ_cnt_16w_wt_2,
  awtpcn.wrk_typ_cnt_16w_wt_3,
  awtpcn.wrk_typ_cnt_16w_wt_4,
  awtpcn.wrk_typ_cnt_16w_wt_5,
  awtpcn.wrk_typ_cnt_30w_1,
  awtpcn.wrk_typ_cnt_30w_2,
  awtpcn.wrk_typ_cnt_30w_3,
  awtpcn.wrk_typ_cnt_30w_4,
  awtpcn.wrk_typ_cnt_30w_5,
  awtpcn.wrk_typ_cnt_30w_wt_1,
  awtpcn.wrk_typ_cnt_30w_wt_2,
  awtpcn.wrk_typ_cnt_30w_wt_3,
  awtpcn.wrk_typ_cnt_30w_wt_4,
  awtpcn.wrk_typ_cnt_30w_wt_5,
  
  awtpdf.wrk_typ_df_avg_1w_1,
  awtpdf.wrk_typ_df_avg_1w_2,
  awtpdf.wrk_typ_df_avg_1w_3,
  awtpdf.wrk_typ_df_avg_1w_4,
  awtpdf.wrk_typ_df_avg_1w_5,
  awtpdf.wrk_typ_df_avg_1w_wt_1,
  awtpdf.wrk_typ_df_avg_1w_wt_2,
  awtpdf.wrk_typ_df_avg_1w_wt_3,
  awtpdf.wrk_typ_df_avg_1w_wt_4,
  awtpdf.wrk_typ_df_avg_1w_wt_5,
  awtpdf.wrk_typ_df_max_1w_1,
  awtpdf.wrk_typ_df_max_1w_2,
  awtpdf.wrk_typ_df_max_1w_3,
  awtpdf.wrk_typ_df_max_1w_4,
  awtpdf.wrk_typ_df_max_1w_5,
  awtpdf.wrk_typ_df_max_1w_wt_1,
  awtpdf.wrk_typ_df_max_1w_wt_2,
  awtpdf.wrk_typ_df_max_1w_wt_3,
  awtpdf.wrk_typ_df_max_1w_wt_4,
  awtpdf.wrk_typ_df_max_1w_wt_5,
  awtpdf.wrk_typ_df_avg_4w_1,
  awtpdf.wrk_typ_df_avg_4w_2,
  awtpdf.wrk_typ_df_avg_4w_3,
  awtpdf.wrk_typ_df_avg_4w_4,
  awtpdf.wrk_typ_df_avg_4w_5,
  awtpdf.wrk_typ_df_avg_4w_wt_1,
  awtpdf.wrk_typ_df_avg_4w_wt_2,
  awtpdf.wrk_typ_df_avg_4w_wt_3,
  awtpdf.wrk_typ_df_avg_4w_wt_4,
  awtpdf.wrk_typ_df_avg_4w_wt_5,
  awtpdf.wrk_typ_df_max_4w_1,
  awtpdf.wrk_typ_df_max_4w_2,
  awtpdf.wrk_typ_df_max_4w_3,
  awtpdf.wrk_typ_df_max_4w_4,
  awtpdf.wrk_typ_df_max_4w_5,
  awtpdf.wrk_typ_df_max_4w_wt_1,
  awtpdf.wrk_typ_df_max_4w_wt_2,
  awtpdf.wrk_typ_df_max_4w_wt_3,
  awtpdf.wrk_typ_df_max_4w_wt_4,
  awtpdf.wrk_typ_df_max_4w_wt_5,
  awtpdf.wrk_typ_df_avg_16w_1,
  awtpdf.wrk_typ_df_avg_16w_2,
  awtpdf.wrk_typ_df_avg_16w_3,
  awtpdf.wrk_typ_df_avg_16w_4,
  awtpdf.wrk_typ_df_avg_16w_5,
  awtpdf.wrk_typ_df_avg_16w_wt_1,
  awtpdf.wrk_typ_df_avg_16w_wt_2,
  awtpdf.wrk_typ_df_avg_16w_wt_3,
  awtpdf.wrk_typ_df_avg_16w_wt_4,
  awtpdf.wrk_typ_df_avg_16w_wt_5,
  awtpdf.wrk_typ_df_max_16w_1,
  awtpdf.wrk_typ_df_max_16w_2,
  awtpdf.wrk_typ_df_max_16w_3,
  awtpdf.wrk_typ_df_max_16w_4,
  awtpdf.wrk_typ_df_max_16w_5,
  awtpdf.wrk_typ_df_max_16w_wt_1,
  awtpdf.wrk_typ_df_max_16w_wt_2,
  awtpdf.wrk_typ_df_max_16w_wt_3,
  awtpdf.wrk_typ_df_max_16w_wt_4,
  awtpdf.wrk_typ_df_max_16w_wt_5,
  awtpdf.wrk_typ_df_avg_30w_2,
  awtpdf.wrk_typ_df_avg_30w_3,
  awtpdf.wrk_typ_df_avg_30w_4,
  awtpdf.wrk_typ_df_avg_30w_5,
  awtpdf.wrk_typ_df_avg_30w_wt_1,
  awtpdf.wrk_typ_df_avg_30w_wt_2,
  awtpdf.wrk_typ_df_avg_30w_wt_3,
  awtpdf.wrk_typ_df_avg_30w_wt_4,
  awtpdf.wrk_typ_df_avg_30w_wt_5,
  awtpdf.wrk_typ_df_max_30w_1,
  awtpdf.wrk_typ_df_max_30w_wt_2,
  awtpdf.wrk_typ_df_max_30w_wt_3,
  awtpdf.wrk_typ_df_max_30w_wt_4,
  awtpdf.wrk_typ_df_max_30w_wt_5,
  
  awtpdu.wrk_typ_dur_1w_1,
  awtpdu.wrk_typ_dur_1w_2,
  awtpdu.wrk_typ_dur_1w_3,
  awtpdu.wrk_typ_dur_1w_4,
  awtpdu.wrk_typ_dur_1w_5,
  awtpdu.wrk_typ_dur_1w_wt_1,
  awtpdu.wrk_typ_dur_1w_wt_2,
  awtpdu.wrk_typ_dur_1w_wt_3,
  awtpdu.wrk_typ_dur_1w_wt_4,
  awtpdu.wrk_typ_dur_1w_wt_5,
  awtpdu.wrk_typ_dur_4w_1,
  awtpdu.wrk_typ_dur_4w_2,
  awtpdu.wrk_typ_dur_4w_3,
  awtpdu.wrk_typ_dur_4w_4,
  awtpdu.wrk_typ_dur_4w_5,
  awtpdu.wrk_typ_dur_4w_wt_1,
  awtpdu.wrk_typ_dur_4w_wt_2,
  awtpdu.wrk_typ_dur_4w_wt_3,
  awtpdu.wrk_typ_dur_4w_wt_4,
  awtpdu.wrk_typ_dur_4w_wt_5,
  awtpdu.wrk_typ_dur_16w_1,
  awtpdu.wrk_typ_dur_16w_2,
  awtpdu.wrk_typ_dur_16w_3,
  awtpdu.wrk_typ_dur_16w_4,
  awtpdu.wrk_typ_dur_16w_5,
  awtpdu.wrk_typ_dur_16w_wt_1,
  awtpdu.wrk_typ_dur_16w_wt_2,
  awtpdu.wrk_typ_dur_16w_wt_3,
  awtpdu.wrk_typ_dur_16w_wt_4,
  awtpdu.wrk_typ_dur_16w_wt_5,
  awtpdu.wrk_typ_dur_30w_1,
  awtpdu.wrk_typ_dur_30w_2,
  awtpdu.wrk_typ_dur_30w_3,
  awtpdu.wrk_typ_dur_30w_4,
  awtpdu.wrk_typ_dur_30w_5,
  awtpdu.wrk_typ_dur_30w_wt_1,
  awtpdu.wrk_typ_dur_30w_wt_2,
  awtpdu.wrk_typ_dur_30w_wt_3,
  awtpdu.wrk_typ_dur_30w_wt_4,
  awtpdu.wrk_typ_dur_30w_wt_5
FROM
  `fluid-door-179122.data_science_dev.master_core_tickets_meta_data` mct

-- V1 features
LEFT JOIN
  `fluid-door-179122.data_science_train.account_final_queue_tix` afq
ON
  mct.tckt_ticketID = afq.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.account_work_difficulty` awd
ON
  mct.tckt_ticketID = awd.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.account_tix_counts` atc
ON
  mct.tckt_ticketID = atc.tckt_ticketID

-- V2 features

LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last5_cnts` awt5c
ON
  mct.tckt_ticketID = awt5c.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last5_df_avg` awt5dv
ON
  mct.tckt_ticketID = awt5dv.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last5_df_max` awt5dm
ON
  mct.tckt_ticketID = awt5dm.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last5_dur` awt5du
ON
  mct.tckt_ticketID = awt5du.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last_period_cnts` awtpcn
ON
  mct.tckt_ticketID = awtpcn.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last_period_df` awtpdf
ON
  mct.tckt_ticketID = awtpdf.tckt_ticketID
LEFT JOIN
  `fluid-door-179122.data_science_train.acct_work_type_last_period_dur` awtpdu
ON
  mct.tckt_ticketID = awtpdu.tckt_ticketID
--ORDER BY
--  Account_Name ASC,
--  tckt_ticketID DESC
  

